<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>

    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>

    <TargetPlatformIdentifier>windows</TargetPlatformIdentifier>
    <TargetPlatformVersion>10.0.19041.0</TargetPlatformVersion>
    <SupportedOSPlatformVersion
      Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">
      10.0.19041.0
    </SupportedOSPlatformVersion>
    <TargetPlatformMinVersion
      Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">
      10.0.19041.0
    </TargetPlatformMinVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <DebugType>full</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DebugSymbols>false</DebugSymbols>
    <DebugType>none</DebugType>
    <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    <Optimize>true</Optimize>
  </PropertyGroup>
</Project>
