<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <ApplicationManifest>Properties/app.manifest</ApplicationManifest>
    <UseWindowsForms>true</UseWindowsForms>

    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
    <_SuppressWinFormsTrimError>true</_SuppressWinFormsTrimError>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Bruno Sales</Authors>
    <Description>
      A modern native pinentry implementation for GnuPG on Windows. Uses Windows
      Credential UI (CredUI) and Windows Hello for a seamless and secure passphrase/PIN entry
      experience.
    </Description>
    <Copyright>Copyright (c) $([System.DateTime]::Now.Year) Bruno Sales &lt;me@baliestri.dev&gt;</Copyright>
    <RepositoryUrl>https://github.com/baliestri/pinentry-for-windows</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Company>baliestri.dev</Company>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AssuanLibrary" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PinentryForWindows.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>
</Project>
